// Code generated by protoc-gen-go.
// source: client_test_param.proto
// DO NOT EDIT!

/*
Package client is a generated protocol buffer package.

It is generated from these files:
	client_test_param.proto

It has these top-level messages:
	ProtoArgs
	ProtoReply
*/
package client

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ProtoArgs struct {
	A int32 `protobuf:"varint,1,opt,name=A" json:"A,omitempty"`
	B int32 `protobuf:"varint,2,opt,name=B" json:"B,omitempty"`
}

func (m *ProtoArgs) Reset()                    { *m = ProtoArgs{} }
func (m *ProtoArgs) String() string            { return proto.CompactTextString(m) }
func (*ProtoArgs) ProtoMessage()               {}
func (*ProtoArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ProtoReply struct {
	C int32 `protobuf:"varint,1,opt,name=C" json:"C,omitempty"`
}

func (m *ProtoReply) Reset()                    { *m = ProtoReply{} }
func (m *ProtoReply) String() string            { return proto.CompactTextString(m) }
func (*ProtoReply) ProtoMessage()               {}
func (*ProtoReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*ProtoArgs)(nil), "client.ProtoArgs")
	proto.RegisterType((*ProtoReply)(nil), "client.ProtoReply")
}

func init() { proto.RegisterFile("client_test_param.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 107 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4f, 0xce, 0xc9, 0x4c,
	0xcd, 0x2b, 0x89, 0x2f, 0x49, 0x2d, 0x2e, 0x89, 0x2f, 0x48, 0x2c, 0x4a, 0xcc, 0xd5, 0x2b, 0x28,
	0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0x48, 0x28, 0xa9, 0x73, 0x71, 0x06, 0x80, 0x04, 0x1c, 0x8b,
	0xd2, 0x8b, 0x85, 0x78, 0xb8, 0x18, 0x1d, 0x25, 0x18, 0x15, 0x18, 0x35, 0x58, 0x83, 0x18, 0x1d,
	0x41, 0x3c, 0x27, 0x09, 0x26, 0x08, 0xcf, 0x49, 0x49, 0x8a, 0x8b, 0x0b, 0xac, 0x30, 0x28, 0xb5,
	0x20, 0xa7, 0x12, 0x24, 0xe7, 0x0c, 0x53, 0xe9, 0x9c, 0xc4, 0x06, 0x36, 0xd3, 0x18, 0x10, 0x00,
	0x00, 0xff, 0xff, 0x3b, 0xf8, 0xf1, 0x5a, 0x6e, 0x00, 0x00, 0x00,
}
